# Generated by Django 3.2.23 on 2024-01-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='button',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
